import 'dotenv/config';
import crypto from 'node:crypto'; import express from 'express'; import http from 'node:http'; import cookieParser from 'cookie-parser'; import jwt from 'jsonwebtoken'; import pg from 'pg'; import {Server} from 'socket.io'; import {OAuth2Client} from 'google-auth-library'; import QRCode from 'qrcode'; import {createClient} from 'redis'; import {createAdapter} from '@socket.io/redis-adapter';
import path from 'node:path';
const app=express(), server=http.createServer(app), io=new Server(server,{maxHttpBufferSize:25e6});
const pool=new pg.Pool({connectionString:process.env.DATABASE_URL}); const google=new OAuth2Client(process.env.GOOGLE_CLIENT_ID); const secret=process.env.JWT_SECRET||'dev-only-change-me';
app.use(express.json({limit:'25mb'})); app.use(cookieParser()); app.use(express.static('public'));
const codeAlphabet='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';
function randomCode(){const b=crypto.randomBytes(8); let s=''; for(let i=0;i<8;i++)s+=codeAlphabet[b[i]%codeAlphabet.length]; return s.slice(0,4)+'-'+s.slice(4)}
function tokenFor(u,identity={}){return jwt.sign({sub:u.id,email:u.email,name:u.display_name,authProvider:identity.authProvider||'dev',googleSub:identity.googleSub||'',emailVerified:Boolean(identity.emailVerified)},secret,{expiresIn:'7d'})}
async function auth(req,res,next){try{req.user=jwt.verify(req.cookies.aj_session||'',secret);const u=await pool.query('SELECT is_suspended FROM users WHERE id=$1',[req.user.sub]);if(!u.rows[0])return res.status(401).json({error:'Account non disponibile'});if(u.rows[0].is_suspended)return res.status(403).json({error:'Account sospeso. Contatta il titolare di AirJotter.'});next()}catch{return res.status(401).json({error:'Autenticazione richiesta'})}}
const PLAN_LIMITS={free:{boards:2,pages:5},plus:{boards:5,pages:10},ultra:{boards:20,pages:50},unlimited:{boards:Number.MAX_SAFE_INTEGER,pages:50}};
const ADMIN_EMAIL='nbochicchio@gmail.com';
function adminOnly(req,res,next){const emailOk=String(req.user?.email||'').toLowerCase()===ADMIN_EMAIL;if(!emailOk)return res.sendStatus(403);if(process.env.NODE_ENV==='production'){const subOk=Boolean(process.env.ADMIN_GOOGLE_SUB)&&req.user.authProvider==='google'&&req.user.emailVerified===true&&req.user.googleSub===process.env.ADMIN_GOOGLE_SUB;if(!subOk)return res.status(403).json({error:'Console riservata al titolare autenticato con Google'})}next()}
async function userPlan(userId){const x=await pool.query('SELECT plan_code FROM users WHERE id=$1',[userId]);return x.rows[0]?.plan_code||'free'}
async function boardPageLimit(boardId){const x=await pool.query('SELECT u.plan_code FROM boards b JOIN users u ON u.id=b.owner_user_id WHERE b.id=$1',[boardId]);return PLAN_LIMITS[x.rows[0]?.plan_code||'free'].pages}

async function activeBoardIds(){
 const ids=new Set();
 for(const [room,sockets] of io.of('/').adapter.rooms){
  if(typeof room!=='string'||!room.startsWith('board:'))continue;
  const boardId=room.slice(6);
  for(const socketId of sockets){const socket=io.of('/').sockets.get(socketId);if(socket?.connected){ids.add(boardId);break}}
 }
 return ids;
}
async function queueEmptyOwnedBoards(userId,currentBoardId=null){
 const active=await activeBoardIds();
 const q=await pool.query(`SELECT b.id FROM boards b
  WHERE b.owner_user_id=$1 AND ($2::uuid IS NULL OR b.id<>$2::uuid)
  AND NOT EXISTS(SELECT 1 FROM board_members bm WHERE bm.board_id=b.id AND bm.user_id<>b.owner_user_id)
  AND NOT EXISTS(SELECT 1 FROM access_requests ar WHERE ar.board_id=b.id AND ar.status='pending')
  AND NOT EXISTS(
   SELECT 1 FROM board_operations bo WHERE bo.board_id=b.id AND bo.is_active=true
   AND bo.operation_type IN ('command:add','stroke:add','text:add')
   AND bo.revision>COALESCE((SELECT max(c.revision) FROM board_operations c WHERE c.board_id=b.id AND c.is_active=true AND c.operation_type='board:clear'),0)
  )`,[userId,currentBoardId]);
 const ids=q.rows.map(x=>x.id);
 if(ids.length)await pool.query("UPDATE boards SET empty_cleanup_after=COALESCE(empty_cleanup_after,now()+interval '30 seconds') WHERE owner_user_id=$1 AND id=ANY($2::uuid[])",[userId,ids]);
 return ids;
}
async function cancelEmptyCleanup(boardId,userId){await pool.query('UPDATE boards SET empty_cleanup_after=NULL WHERE id=$1 AND owner_user_id=$2',[boardId,userId])}
async function deleteDueEmptyBoards(){
 const active=await activeBoardIds();
 const q=await pool.query(`SELECT b.id,b.owner_user_id FROM boards b WHERE b.empty_cleanup_after<=now()
  AND NOT EXISTS(SELECT 1 FROM board_members bm WHERE bm.board_id=b.id AND bm.user_id<>b.owner_user_id)
  AND NOT EXISTS(SELECT 1 FROM access_requests ar WHERE ar.board_id=b.id AND ar.status='pending')
  AND NOT EXISTS(
   SELECT 1 FROM board_operations bo WHERE bo.board_id=b.id AND bo.is_active=true
   AND bo.operation_type IN ('command:add','stroke:add','text:add')
   AND bo.revision>COALESCE((SELECT max(c.revision) FROM board_operations c WHERE c.board_id=b.id AND c.is_active=true AND c.operation_type='board:clear'),0)
  )`);
 const ids=q.rows.map(x=>x.id).filter(id=>!active.has(id));
 if(ids.length)await pool.query('DELETE FROM boards WHERE id=ANY($1::uuid[])',[ids]);return ids;
}
async function cleanupOwnerEmptyBoardsNow(userId){
 const q=await pool.query(`SELECT b.id FROM boards b WHERE b.owner_user_id=$1
 AND NOT EXISTS(SELECT 1 FROM board_members bm WHERE bm.board_id=b.id AND bm.user_id<>b.owner_user_id)
 AND NOT EXISTS(SELECT 1 FROM access_requests ar WHERE ar.board_id=b.id AND ar.status='pending')
 AND NOT EXISTS(SELECT 1 FROM board_operations bo WHERE bo.board_id=b.id AND bo.is_active=true
   AND bo.operation_type IN ('command:add','stroke:add','text:add')
   AND bo.revision>COALESCE((SELECT max(c.revision) FROM board_operations c WHERE c.board_id=b.id AND c.is_active=true AND c.operation_type='board:clear'),0))`,[userId]);
 const ids=q.rows.map(x=>x.id);if(ids.length)await pool.query('DELETE FROM boards WHERE owner_user_id=$1 AND id=ANY($2::uuid[])',[userId,ids]);return ids;
}
async function role(boardId,userId){const q=await pool.query('SELECT role,status FROM board_members WHERE board_id=$1 AND user_id=$2',[boardId,userId]); return q.rows[0]}
app.get('/privacy',(req,res)=>res.sendFile(path.join(process.cwd(),'public','privacy.html')));
app.get('/terms',(req,res)=>res.sendFile(path.join(process.cwd(),'public','terms.html')));
app.post('/api/boards/cleanup-empty',auth,async(req,res)=>{const queued=await queueEmptyOwnedBoards(req.user.sub,req.body?.currentBoardId||null);res.json({queued})});
app.get('/api/health',(req,res)=>res.json({ok:true}));
app.get('/api/config',(req,res)=>res.json({googleClientId:process.env.GOOGLE_CLIENT_ID||'',devAuth:process.env.DEV_AUTH==='true'}));
app.post('/api/auth/google',async(req,res)=>{try{const t=await google.verifyIdToken({idToken:req.body.credential,audience:process.env.GOOGLE_CLIENT_ID}); const p=t.getPayload(); if(!p?.sub||!p?.email||p.email_verified!==true)return res.status(401).json({error:'Account Google senza email verificata'}); const id=crypto.randomUUID(); const q=await pool.query(`INSERT INTO users(id,google_sub,email,display_name,avatar_url) VALUES($1,$2,$3,$4,$5) ON CONFLICT(google_sub) DO UPDATE SET email=EXCLUDED.email,display_name=EXCLUDED.display_name,avatar_url=EXCLUDED.avatar_url RETURNING *`,[id,p.sub,p.email,p.name||p.email,p.picture||null]); await pool.query('UPDATE users SET last_login_at=now() WHERE id=$1',[q.rows[0].id]);await pool.query('INSERT INTO login_events(id,user_id) VALUES($1,$2)',[crypto.randomUUID(),q.rows[0].id]);res.cookie('aj_session',tokenFor(q.rows[0],{authProvider:'google',googleSub:p.sub,emailVerified:p.email_verified===true}),{httpOnly:true,secure:process.env.NODE_ENV==='production',sameSite:'lax',maxAge:604800000});res.json({ok:true,user:q.rows[0]})}catch(error){console.error('Verifica Google:',error.message);res.status(401).json({error:'Credenziale Google non valida'})}});
app.post('/api/auth/dev',async(req,res)=>{try{if(process.env.DEV_AUTH!=='true')return res.status(404).json({error:'Accesso test disattivato'});const email=String(req.body.email||'demo@airjotter.local').trim().toLowerCase();const name=String(req.body.name||email.split('@')[0]).trim();if(!email||!name)return res.status(400).json({error:'Nome ed email sono obbligatori'});const id=crypto.randomUUID();const query=await pool.query(`INSERT INTO users(id,email,display_name) VALUES($1,$2,$3) ON CONFLICT(email) DO UPDATE SET display_name=EXCLUDED.display_name RETURNING *`,[id,email,name]);const user=query.rows[0];if(user.is_suspended)return res.status(403).json({error:'Account sospeso. Contatta il titolare di AirJotter.'});if(user.is_suspended)return res.status(403).json({error:'Account sospeso. Contatta il titolare di AirJotter.'});try{await pool.query('UPDATE users SET last_login_at=now() WHERE id=$1',[user.id]);await pool.query('INSERT INTO login_events(id,user_id) VALUES($1,$2)',[crypto.randomUUID(),user.id])}catch(metricError){console.warn('Metriche accesso non registrate:',metricError.message)}res.cookie('aj_session',tokenFor(user),{httpOnly:true,secure:process.env.NODE_ENV==='production',sameSite:'lax',maxAge:604800000});res.json({ok:true,user})}catch(error){console.error('Errore accesso sviluppo:',error);res.status(500).json({error:'Accesso non riuscito: '+error.message})}});
app.get('/api/me',auth,async(req,res)=>{await deleteDueEmptyBoards();const isAdmin=String(req.user.email||'').toLowerCase()===ADMIN_EMAIL;const plan=isAdmin?'unlimited':await userPlan(req.user.sub);if(isAdmin)await pool.query("UPDATE users SET plan_code='unlimited' WHERE id=$1",[req.user.sub]);res.json({...req.user,plan,limits:PLAN_LIMITS[plan],isAdmin})});
app.post('/api/boards',auth,async(req,res)=>{await deleteDueEmptyBoards();const plan=await userPlan(req.user.sub),isOwner=String(req.user.email||'').toLowerCase()===ADMIN_EMAIL,limit=isOwner?Number.MAX_SAFE_INTEGER:PLAN_LIMITS[plan].boards,count=Number((await pool.query('SELECT count(*) FROM boards WHERE owner_user_id=$1',[req.user.sub])).rows[0].count);if(count>=limit)return res.status(403).json({error:`Il piano ${plan.toUpperCase()} consente massimo ${limit} Jotter di proprietÃ .`});for(let i=0;i<12;i++){const id=crypto.randomUUID(),code=randomCode();try{await pool.query('BEGIN');await pool.query('INSERT INTO boards(id,room_code,owner_user_id,title) VALUES($1,$2,$3,$4)',[id,code,req.user.sub,req.body.title||'Jotter senza titolo']);await pool.query("INSERT INTO board_members(board_id,user_id,role,status) VALUES($1,$2,'owner','approved')",[id,req.user.sub]);await pool.query('COMMIT');return res.status(201).json({id,roomCode:code,url:`${process.env.APP_URL}/?room=${code}`,role:'owner'})}catch(e){await pool.query('ROLLBACK');if(e.code!=='23505')throw e}}res.status(503).json({error:'Impossibile generare un codice univoco'})});
app.post('/api/boards/join',auth,async(req,res)=>{const raw=String(req.body.roomCode||'').trim().toUpperCase().replace(/[^A-Z0-9]/g,'');const c=raw.length===8?raw.slice(0,4)+'-'+raw.slice(4):String(req.body.roomCode||'').trim().toUpperCase();const q=await pool.query('SELECT * FROM boards WHERE room_code=$1',[c]);if(!q.rows[0])return res.status(404).json({error:'Jotter non trovato'});const b=q.rows[0];if(b.owner_user_id===req.user.sub)await cancelEmptyCleanup(b.id,req.user.sub);await pool.query("INSERT INTO board_members(board_id,user_id,role,status) VALUES($1,$2,'viewer','approved') ON CONFLICT DO NOTHING",[b.id,req.user.sub]);const r=await role(b.id,req.user.sub);if(!r||r.status==='revoked')return res.status(403).json({error:'Accesso a questo Jotter sospeso dal proprietario'});res.json({id:b.id,roomCode:b.room_code,title:b.title,revision:b.revision,role:r.role})});
app.get('/api/my/boards',auth,async(req,res)=>{await deleteDueEmptyBoards();const q=await pool.query('SELECT b.id,b.room_code,b.title,b.created_at,b.content_updated_at,u.display_name AS owner_name FROM boards b JOIN users u ON u.id=b.owner_user_id WHERE b.owner_user_id=$1 ORDER BY b.content_updated_at DESC',[req.user.sub]);res.json(q.rows.map(x=>({id:x.id,roomCode:x.room_code,title:x.title,createdAt:x.created_at,contentUpdatedAt:x.content_updated_at,ownerName:x.owner_name})))});
app.patch('/api/boards/:id/title',auth,async(req,res)=>{const title=String(req.body.title||'').trim().slice(0,120);if(!title)return res.status(400).json({error:'Titolo non valido'});const q=await pool.query('UPDATE boards SET title=$1 WHERE id=$2 AND owner_user_id=$3 RETURNING id,title,content_updated_at',[title,req.params.id,req.user.sub]);if(!q.rows[0])return res.sendStatus(403);res.json({id:q.rows[0].id,title:q.rows[0].title,contentUpdatedAt:q.rows[0].content_updated_at})});
app.delete('/api/boards/:id',auth,async(req,res)=>{const q=await pool.query('DELETE FROM boards WHERE id=$1 AND owner_user_id=$2 RETURNING id',[req.params.id,req.user.sub]);if(!q.rows[0])return res.sendStatus(403);res.json({deleted:true,id:q.rows[0].id})});
app.get('/api/admin/stats',auth,adminOnly,async(req,res)=>{const [u,b,l,o,p]=await Promise.all([pool.query("SELECT count(*)::int total,count(*) FILTER(WHERE created_at>=current_date)::int today,count(*) FILTER(WHERE created_at>=now()-interval '7 days')::int week FROM users"),pool.query("SELECT count(*)::int total,count(*) FILTER(WHERE created_at>=current_date)::int today,count(*) FILTER(WHERE content_updated_at>=now()-interval '24 hours')::int active FROM boards"),pool.query("SELECT count(*)::int total,count(*) FILTER(WHERE created_at>=current_date)::int today,count(DISTINCT user_id) FILTER(WHERE created_at>=now()-interval '24 hours')::int active_users FROM login_events"),pool.query('SELECT count(*)::int total FROM board_operations'),pool.query('SELECT plan_code,count(*)::int count FROM users GROUP BY plan_code')]);res.json({users:u.rows[0],boards:b.rows[0],logins:l.rows[0],operations:o.rows[0].total,plans:p.rows,online:io.engine.clientsCount,updatedAt:new Date().toISOString()})});
app.get('/api/admin/users',auth,adminOnly,async(req,res)=>{const x=await pool.query('SELECT u.id,u.email,u.display_name,u.plan_code,u.created_at,u.last_login_at,u.is_suspended,count(b.id)::int AS boards FROM users u LEFT JOIN boards b ON b.owner_user_id=u.id GROUP BY u.id ORDER BY u.created_at DESC LIMIT 500');res.json(x.rows.map(r=>({id:r.id,email:r.email,name:r.display_name,plan:r.plan_code,createdAt:r.created_at,lastLoginAt:r.last_login_at,suspended:r.is_suspended,boards:r.boards}))) });
app.patch('/api/admin/users/:id/suspension',auth,adminOnly,async(req,res)=>{const target=await pool.query('SELECT id,email,is_suspended FROM users WHERE id=$1',[req.params.id]);const u=target.rows[0];if(!u)return res.sendStatus(404);if(String(u.email).toLowerCase()===ADMIN_EMAIL)return res.status(400).json({error:'Il titolare non puÃ² essere sospeso'});const suspended=Boolean(req.body.suspended);const x=await pool.query('UPDATE users SET is_suspended=$1,suspended_at=CASE WHEN $1 THEN now() ELSE NULL END WHERE id=$2 RETURNING id,email,is_suspended',[suspended,u.id]);if(suspended){for(const [id,socket] of io.of('/').sockets){if(socket.user?.sub===u.id){socket.emit('account:suspended');socket.disconnect(true)}}}res.json({id:x.rows[0].id,email:x.rows[0].email,suspended:x.rows[0].is_suspended})});
app.delete('/api/admin/users/:id',auth,adminOnly,async(req,res)=>{const client=await pool.connect();try{await client.query('BEGIN');const target=await client.query('SELECT id,email FROM users WHERE id=$1 FOR UPDATE',[req.params.id]);const u=target.rows[0];if(!u){await client.query('ROLLBACK');return res.sendStatus(404)}if(String(u.email).toLowerCase()===ADMIN_EMAIL){await client.query('ROLLBACK');return res.status(400).json({error:'Il titolare non puÃ² essere eliminato'})}for(const [socketId,socket] of io.of('/').sockets){if(socket.user?.sub===u.id){socket.emit('account:deleted');socket.disconnect(true)}}await client.query('DELETE FROM boards WHERE owner_user_id=$1',[u.id]);await client.query('DELETE FROM board_members WHERE user_id=$1',[u.id]);await client.query('DELETE FROM access_requests WHERE requester_user_id=$1',[u.id]);await client.query('DELETE FROM login_events WHERE user_id=$1',[u.id]);await client.query('DELETE FROM users WHERE id=$1',[u.id]);await client.query('COMMIT');res.json({deleted:true,id:u.id})}catch(error){await client.query('ROLLBACK');console.error('Eliminazione utente:',error);res.status(500).json({error:'Eliminazione non riuscita: '+error.message})}finally{client.release()}});

app.get('/api/boards/:id/access',auth,async(req,res)=>{
 const b=(await pool.query('SELECT id,title,room_code,owner_user_id FROM boards WHERE id=$1',[req.params.id])).rows[0];
 if(!b)return res.sendStatus(404);if(b.owner_user_id!==req.user.sub)return res.sendStatus(403);
 const members=await pool.query("SELECT bm.user_id,bm.role,bm.status,u.display_name,u.email FROM board_members bm JOIN users u ON u.id=bm.user_id WHERE bm.board_id=$1 ORDER BY CASE bm.role WHEN 'owner' THEN 0 WHEN 'editor' THEN 1 ELSE 2 END,u.display_name",[b.id]);
 const requests=await pool.query("SELECT ar.id,ar.requester_user_id,u.display_name,u.email,ar.created_at FROM access_requests ar JOIN users u ON u.id=ar.requester_user_id WHERE ar.board_id=$1 AND ar.status='pending' ORDER BY ar.created_at",[b.id]);
 res.json({id:b.id,title:b.title,roomCode:b.room_code,members:members.rows.map(x=>({userId:x.user_id,name:x.display_name,email:x.email,role:x.role,status:x.status})),requests:requests.rows.map(x=>({requestId:x.id,userId:x.requester_user_id,name:x.display_name,email:x.email,createdAt:x.created_at}))});
});
app.patch('/api/boards/:id/members/:userId/suspension',auth,async(req,res)=>{
 const b=(await pool.query('SELECT owner_user_id FROM boards WHERE id=$1',[req.params.id])).rows[0];if(!b)return res.sendStatus(404);if(b.owner_user_id!==req.user.sub)return res.sendStatus(403);if(req.params.userId===req.user.sub)return res.status(400).json({error:'Il proprietario non puÃ² essere sospeso'});
 const suspended=Boolean(req.body.suspended);const q=await pool.query("UPDATE board_members SET status=$1 WHERE board_id=$2 AND user_id=$3 AND role<>'owner' RETURNING user_id,role,status",[suspended?'revoked':'approved',req.params.id,req.params.userId]);if(!q.rows[0])return res.sendStatus(404);
 if(suspended){io.to('user:'+req.params.userId).emit('board:access-suspended',{boardId:req.params.id});}else{io.to('user:'+req.params.userId).emit('board:access-restored',{boardId:req.params.id,role:q.rows[0].role});}res.json({ok:true,suspended,status:q.rows[0].status});
});
app.delete('/api/boards/:id/members/:userId',auth,async(req,res)=>{
 const b=(await pool.query('SELECT owner_user_id FROM boards WHERE id=$1',[req.params.id])).rows[0];if(!b)return res.sendStatus(404);if(b.owner_user_id!==req.user.sub)return res.sendStatus(403);if(req.params.userId===req.user.sub)return res.status(400).json({error:'Il proprietario non puÃ² essere eliminato'});
 await pool.query('BEGIN');try{await pool.query('DELETE FROM access_requests WHERE board_id=$1 AND requester_user_id=$2',[req.params.id,req.params.userId]);const q=await pool.query("DELETE FROM board_members WHERE board_id=$1 AND user_id=$2 AND role<>'owner' RETURNING user_id",[req.params.id,req.params.userId]);await pool.query('COMMIT');if(!q.rows[0])return res.sendStatus(404);io.to('user:'+req.params.userId).emit('board:access-removed',{boardId:req.params.id});res.json({deleted:true})}catch(e){await pool.query('ROLLBACK');throw e}
});
app.get('/api/boards/:id/history-state',auth,async(req,res)=>{const r=await role(req.params.id,req.user.sub);if(!r||r.status!=='approved')return res.sendStatus(403);const q=await pool.query('SELECT count(*) FILTER(WHERE is_active=true)::int AS active,count(*) FILTER(WHERE is_active=false)::int AS inactive FROM board_operations WHERE board_id=$1',[req.params.id]);res.json({canUndo:q.rows[0].active>0,canRedo:q.rows[0].inactive>0})});
app.get('/api/boards/:id/operations',auth,async(req,res)=>{const r=await role(req.params.id,req.user.sub);if(!r||r.status!=='approved')return res.sendStatus(403);const q=await pool.query('SELECT revision,operation_id,operation_type,payload,is_active FROM board_operations WHERE board_id=$1 ORDER BY revision',[req.params.id]);res.json(q.rows)});
app.get('/api/boards/:id/qr',auth,async(req,res)=>{const r=await role(req.params.id,req.user.sub);if(!r)return res.sendStatus(403);const q=await pool.query('SELECT room_code FROM boards WHERE id=$1',[req.params.id]);if(!q.rows[0])return res.sendStatus(404);res.type('png');res.send(await QRCode.toBuffer(`${process.env.APP_URL}/?room=${q.rows[0].room_code}`,{width:320,margin:2}))});
app.post('/api/boards/:id/request-edit',auth,async(req,res)=>{const r=await role(req.params.id,req.user.sub);if(!r)return res.sendStatus(403);if(r.role!=='viewer')return res.json({status:r.role});let q=await pool.query("SELECT id FROM access_requests WHERE board_id=$1 AND requester_user_id=$2 AND status='pending'",[req.params.id,req.user.sub]);let id=q.rows[0]?.id;if(!id){id=crypto.randomUUID();await pool.query("INSERT INTO access_requests(id,board_id,requester_user_id) VALUES($1,$2,$3)",[id,req.params.id,req.user.sub]);}const b=await pool.query('SELECT owner_user_id FROM boards WHERE id=$1',[req.params.id]);const event={requestId:id,boardId:req.params.id,name:req.user.name,email:req.user.email};io.to('user:'+b.rows[0].owner_user_id).emit('access:requested',event);res.json({status:'pending',requestId:id})});
app.get('/api/boards/:id/access-requests',auth,async(req,res)=>{const b=await pool.query('SELECT owner_user_id FROM boards WHERE id=$1',[req.params.id]);if(!b.rows[0]||b.rows[0].owner_user_id!==req.user.sub)return res.sendStatus(403);const q=await pool.query("SELECT ar.id,ar.board_id,u.display_name,u.email FROM access_requests ar JOIN users u ON u.id=ar.requester_user_id WHERE ar.board_id=$1 AND ar.status='pending' ORDER BY ar.created_at",[req.params.id]);res.json(q.rows.map(x=>({requestId:x.id,boardId:x.board_id,name:x.display_name,email:x.email})))});
app.post('/api/access/:id/resolve',auth,async(req,res)=>{const q=await pool.query('SELECT ar.*,b.owner_user_id FROM access_requests ar JOIN boards b ON b.id=ar.board_id WHERE ar.id=$1',[req.params.id]);const a=q.rows[0];if(!a||a.owner_user_id!==req.user.sub)return res.sendStatus(403);const approved=!!req.body.approved;await pool.query('BEGIN');await pool.query("UPDATE access_requests SET status=$1,resolved_at=now() WHERE id=$2 AND status='pending'",[approved?'approved':'denied',a.id]);if(approved)await pool.query("UPDATE board_members SET role='editor',status='approved' WHERE board_id=$1 AND user_id=$2",[a.board_id,a.requester_user_id]);await pool.query('COMMIT');io.to(`user:${a.requester_user_id}`).emit('access:resolved',{boardId:a.board_id,approved,role:approved?'editor':'viewer'});res.json({approved})});
io.use(async(socket,next)=>{try{const raw=socket.handshake.headers.cookie||'';const m=raw.match(/(?:^|; )aj_session=([^;]+)/);socket.user=jwt.verify(decodeURIComponent(m?.[1]||''),secret);const u=await pool.query('SELECT is_suspended FROM users WHERE id=$1',[socket.user.sub]);if(!u.rows[0]||u.rows[0].is_suspended)return next(new Error('account_suspended'));next()}catch{next(new Error('unauthorized'))}});
const pub=createClient({url:process.env.REDIS_URL}),sub=pub.duplicate();await Promise.all([pub.connect(),sub.connect()]);io.adapter(createAdapter(pub,sub));
io.on('connection',socket=>{socket.join(`user:${socket.user.sub}`);socket.on('board:join',async({boardId},ack)=>{const r=await role(boardId,socket.user.sub);if(!r||r.status!=='approved')return ack?.({error:'forbidden'});socket.join(`board:${boardId}`);socket.data.currentBoardId=boardId;const own=await pool.query('SELECT owner_user_id FROM boards WHERE id=$1',[boardId]);if(own.rows[0]?.owner_user_id===socket.user.sub)await cancelEmptyCleanup(boardId,socket.user.sub);ack?.({ok:true,role:r.role})});socket.on('disconnect',()=>{const boardId=socket.data.currentBoardId,userId=socket.user.sub;if(!boardId)return;setTimeout(async()=>{try{const own=await pool.query('SELECT owner_user_id FROM boards WHERE id=$1',[boardId]);if(own.rows[0]?.owner_user_id!==userId)return;const room=io.of('/').adapter.rooms.get('board:'+boardId);if(!room||room.size===0)await queueEmptyOwnedBoards(userId,null)}catch(e){console.warn('Accodamento Jotter vuoto:',e.message)}},1000)});socket.on('board:operation',async(op,ack)=>{try{const r=await role(op.boardId,socket.user.sub);if(!r||!['owner','editor'].includes(r.role))return ack?.({error:'readonly'});if(!['stroke:add','text:add','command:add','page:set','page:delete','board:clear'].includes(op.type))return ack?.({error:'invalid'});if(op.type==='page:set'){const maxPages=await boardPageLimit(op.boardId);if(Number(op.payload?.count)>maxPages)return ack?.({error:'page_limit',message:`Il piano del proprietario consente massimo ${maxPages} pagine.`});}const c=await pool.connect();try{await c.query('BEGIN');await c.query('DELETE FROM board_operations WHERE board_id=$1 AND is_active=false',[op.boardId]);const b=await c.query('UPDATE boards SET revision=revision+1,updated_at=now(),content_updated_at=now(),empty_cleanup_after=NULL WHERE id=$1 RETURNING revision',[op.boardId]);const rev=b.rows[0].revision;await c.query('INSERT INTO board_operations(board_id,revision,operation_id,user_id,operation_type,payload) VALUES($1,$2,$3,$4,$5,$6)',[op.boardId,rev,op.operationId,socket.user.sub,op.type,op.payload]);await c.query('COMMIT');const event={...op,revision:rev};socket.to(`board:${op.boardId}`).emit('board:operation',event);ack?.({ok:true,revision:rev})}catch(e){await c.query('ROLLBACK');throw e}finally{c.release()}}catch{ack?.({error:'server'})}});
 socket.on('history:undo',async({boardId},ack)=>{try{const r=await role(boardId,socket.user.sub);if(!r||!['owner','editor'].includes(r.role))return ack?.({error:'readonly'});const q=await pool.query(`UPDATE board_operations SET is_active=false WHERE board_id=$1 AND revision=(SELECT max(revision) FROM board_operations WHERE board_id=$1 AND is_active=true) RETURNING operation_id`,[boardId]);if(q.rowCount){io.to(`board:${boardId}`).emit('board:reload');const st=await pool.query('SELECT count(*) FILTER(WHERE is_active=true)::int active,count(*) FILTER(WHERE is_active=false)::int inactive FROM board_operations WHERE board_id=$1',[boardId]);ack?.({ok:true,canUndo:st.rows[0].active>0,canRedo:st.rows[0].inactive>0})}else ack?.({error:'empty',canUndo:false,canRedo:false})}catch{ack?.({error:'server'})}});
 socket.on('history:redo',async({boardId},ack)=>{try{const r=await role(boardId,socket.user.sub);if(!r||!['owner','editor'].includes(r.role))return ack?.({error:'readonly'});const q=await pool.query(`UPDATE board_operations SET is_active=true WHERE board_id=$1 AND revision=(SELECT min(revision) FROM board_operations WHERE board_id=$1 AND is_active=false) RETURNING operation_id`,[boardId]);if(q.rowCount){io.to(`board:${boardId}`).emit('board:reload');const st=await pool.query('SELECT count(*) FILTER(WHERE is_active=true)::int active,count(*) FILTER(WHERE is_active=false)::int inactive FROM board_operations WHERE board_id=$1',[boardId]);ack?.({ok:true,canUndo:st.rows[0].active>0,canRedo:st.rows[0].inactive>0})}else ack?.({error:'empty',canUndo:true,canRedo:false})}catch{ack?.({error:'server'})}})
});
setInterval(()=>deleteDueEmptyBoards().then(ids=>{if(ids.length)console.log('Jotter vuoti eliminati:',ids.join(','))}).catch(e=>console.warn('Pulizia Jotter vuoti:',e.message)),10000);
if(process.env.NODE_ENV==='production'&&process.env.DEV_AUTH==='true')throw new Error('Configurazione non sicura: DEV_AUTH non puÃ² essere attivo in produzione');
if(process.env.NODE_ENV==='production'&&!process.env.ADMIN_GOOGLE_SUB)throw new Error('ADMIN_GOOGLE_SUB obbligatorio in produzione');
server.listen(process.env.PORT||3000,()=>console.log(`airjotter su porta ${process.env.PORT||3000}`));
