import 'dotenv/config';
import crypto from 'node:crypto'; import express from 'express'; import http from 'node:http'; import cookieParser from 'cookie-parser'; import jwt from 'jsonwebtoken'; import pg from 'pg'; import {Server} from 'socket.io'; import {OAuth2Client} from 'google-auth-library'; import QRCode from 'qrcode'; import {createClient} from 'redis'; import {createAdapter} from '@socket.io/redis-adapter';
import path from 'node:path';
import Stripe from 'stripe';
const app=express(), server=http.createServer(app), io=new Server(server,{maxHttpBufferSize:25e6,connectionStateRecovery:{maxDisconnectionDuration:120000,skipMiddlewares:false}});
const pool=new pg.Pool({connectionString:process.env.DATABASE_URL}); const google=new OAuth2Client(process.env.GOOGLE_CLIENT_ID); const secret=process.env.JWT_SECRET||'dev-only-change-me';
const stripe=process.env.STRIPE_SECRET_KEY?new Stripe(process.env.STRIPE_SECRET_KEY):null;
const appBaseUrl=process.env.APP_BASE_URL||process.env.APP_URL||'http://localhost:3000';
app.post('/api/billing/stripe/webhook',express.raw({type:'application/json'}),stripeWebhookHandler);
app.use(express.json({limit:'25mb'})); app.use(cookieParser()); app.use(express.static('public'));
const codeAlphabet='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';
function randomCode(){const b=crypto.randomBytes(8); let s=''; for(let i=0;i<8;i++)s+=codeAlphabet[b[i]%codeAlphabet.length]; return s.slice(0,4)+'-'+s.slice(4)}
function tokenFor(u,identity={}){return jwt.sign({sub:u.id,email:u.email,name:u.display_name,authProvider:identity.authProvider||'dev',googleSub:identity.googleSub||'',emailVerified:Boolean(identity.emailVerified)},secret,{expiresIn:'7d'})}
async function auth(req,res,next){try{req.user=jwt.verify(req.cookies.aj_session||'',secret);const u=await pool.query('SELECT is_suspended FROM users WHERE id=$1',[req.user.sub]);if(!u.rows[0])return res.status(401).json({error:'Account non disponibile'});if(u.rows[0].is_suspended)return res.status(403).json({error:'Account sospeso. Contatta il titolare di AirJotter.'});next()}catch{return res.status(401).json({error:'Autenticazione richiesta'})}}
const PLAN_LIMITS={free:{boards:2,pages:5},plus:{boards:5,pages:10},ultra:{boards:20,pages:50},unlimited:{boards:Number.MAX_SAFE_INTEGER,pages:50}};
const ADMIN_EMAIL='nbochicchio@gmail.com';
function adminOnly(req,res,next){const emailOk=String(req.user?.email||'').toLowerCase()===ADMIN_EMAIL;if(!emailOk)return res.sendStatus(403);if(process.env.NODE_ENV==='production'){const subOk=Boolean(process.env.ADMIN_GOOGLE_SUB)&&req.user.authProvider==='google'&&req.user.emailVerified===true&&req.user.googleSub===process.env.ADMIN_GOOGLE_SUB;if(!subOk)return res.status(403).json({error:'Consolle riservata al titolare autenticato con Google'})}next()}
async function resolvedPlan(userId){const q=await pool.query(`SELECT u.plan_code,u.spot_jotters,u.spot_pages,u.spot_exports,u.spot_credit_cents,p.* FROM users u LEFT JOIN billing_plans p ON p.id=u.plan_id WHERE u.id=$1`,[userId]);const r=q.rows[0]||{};const fallback=PLAN_LIMITS[r.plan_code]||PLAN_LIMITS.free;return {id:r.id||null,code:r.code||r.plan_code||'free',name:r.name||r.plan_code||'Free',boards:Number(r.boards_limit||fallback.boards),pages:Number(r.pages_limit||fallback.pages),spotJotters:Number(r.spot_jotters||0),spotPages:Number(r.spot_pages||0),spotExports:Number(r.spot_exports||0),spotCreditCents:Number(r.spot_credit_cents||0),status:r.status||'active'};}
async function userPlan(userId){return (await resolvedPlan(userId)).code}
async function boardPageLimit(boardId){const x=await pool.query('SELECT owner_user_id FROM boards WHERE id=$1',[boardId]);if(!x.rows[0])return PLAN_LIMITS.free.pages;const p=await resolvedPlan(x.rows[0].owner_user_id);return p.pages+p.spotPages}

async function activeBoardIds(){
 const ids=new Set();
 for(const [room,sockets] of io.of('/').adapter.rooms){
  if(typeof room!=='string'||!room.startsWith('board:'))continue;
  const boardId=room.slice(6);
  for(const socketId of sockets){const socket=io.of('/').sockets.get(socketId);if(socket?.connected){ids.add(boardId);break}}
 }
 return ids;
}
async function queueEmptyOwnedBoards(userId,currentBoardId=null){
 const active=await activeBoardIds();
 const q=await pool.query(`SELECT b.id FROM boards b
  WHERE b.owner_user_id=$1 AND ($2::uuid IS NULL OR b.id<>$2::uuid)
  AND NOT EXISTS(SELECT 1 FROM board_members bm WHERE bm.board_id=b.id AND bm.user_id<>b.owner_user_id)
  AND NOT EXISTS(SELECT 1 FROM access_requests ar WHERE ar.board_id=b.id AND ar.status='pending')
  AND NOT EXISTS(
   SELECT 1 FROM board_operations bo WHERE bo.board_id=b.id AND bo.is_active=true
   AND bo.operation_type IN ('command:add','stroke:add','text:add')
   AND bo.revision>COALESCE((SELECT max(c.revision) FROM board_operations c WHERE c.board_id=b.id AND c.is_active=true AND c.operation_type='board:clear'),0)
  )`,[userId,currentBoardId]);
 const ids=q.rows.map(x=>x.id);
 if(ids.length)await pool.query("UPDATE boards SET empty_cleanup_after=COALESCE(empty_cleanup_after,now()+interval '30 seconds') WHERE owner_user_id=$1 AND id=ANY($2::uuid[])",[userId,ids]);
 return ids;
}
async function cancelEmptyCleanup(boardId,userId){await pool.query('UPDATE boards SET empty_cleanup_after=NULL WHERE id=$1 AND owner_user_id=$2',[boardId,userId])}
async function deleteDueEmptyBoards(){
 const active=await activeBoardIds();
 const q=await pool.query(`SELECT b.id,b.owner_user_id FROM boards b WHERE b.empty_cleanup_after<=now()
  AND NOT EXISTS(SELECT 1 FROM board_members bm WHERE bm.board_id=b.id AND bm.user_id<>b.owner_user_id)
  AND NOT EXISTS(SELECT 1 FROM access_requests ar WHERE ar.board_id=b.id AND ar.status='pending')
  AND NOT EXISTS(
   SELECT 1 FROM board_operations bo WHERE bo.board_id=b.id AND bo.is_active=true
   AND bo.operation_type IN ('command:add','stroke:add','text:add')
   AND bo.revision>COALESCE((SELECT max(c.revision) FROM board_operations c WHERE c.board_id=b.id AND c.is_active=true AND c.operation_type='board:clear'),0)
  )`);
 const ids=q.rows.map(x=>x.id).filter(id=>!active.has(id));
 if(ids.length)await pool.query('DELETE FROM boards WHERE id=ANY($1::uuid[])',[ids]);return ids;
}
// AIRJOTTER_SERVER_V224_REALTIME_INK
// AIRJOTTER_SERVER_V158
async function cleanupOwnerEmptyBoardsNow(userId){
 const q=await pool.query(`DELETE FROM boards b WHERE b.owner_user_id=$1 AND b.is_empty=true AND b.is_current=false RETURNING b.id`,[userId]);
 return q.rows.map(x=>x.id);
}
async function startupCleanup(userId){
 try{return await cleanupOwnerEmptyBoardsNow(userId)}catch(e){console.warn('Pulizia avvio non bloccante:',e.message);return []}
}
async function role(boardId,userId){const q=await pool.query('SELECT role,status FROM board_members WHERE board_id=$1 AND user_id=$2',[boardId,userId]); return q.rows[0]}

function planPublic(row){return {id:row.id,code:row.code,name:row.name,description:row.description,status:row.status,billingType:row.billing_type,currency:row.currency,amountCents:Number(row.amount_cents),intervalUnit:row.interval_unit,intervalCount:Number(row.interval_count||1),minSeats:Number(row.min_seats||1),maxSeats:row.max_seats==null?null:Number(row.max_seats),limits:{boards:Number(row.boards_limit),pages:Number(row.pages_limit),guests:row.guests_limit,exports:row.exports_limit,historyDays:row.history_days},included:{jotters:Number(row.included_spot_jotters||0),pages:Number(row.included_spot_pages||0),exports:Number(row.included_spot_exports||0)},features:Array.isArray(row.features)?row.features:[],consumableKind:row.consumable_kind,consumableUnits:Number(row.consumable_units||0),sortOrder:Number(row.sort_order||0),featured:Boolean(row.featured),public:Boolean(row.public),stripeReady:Boolean(row.stripe_price_id),paypalReady:Boolean(row.paypal_plan_id)}}
async function planById(id){return (await pool.query('SELECT * FROM billing_plans WHERE id=$1',[id])).rows[0]}
async function paypalToken(){if(!process.env.PAYPAL_CLIENT_ID||!process.env.PAYPAL_CLIENT_SECRET)return null;const base=process.env.PAYPAL_ENV==='live'?'https://api-m.paypal.com':'https://api-m.sandbox.paypal.com';const auth=Buffer.from(process.env.PAYPAL_CLIENT_ID+':'+process.env.PAYPAL_CLIENT_SECRET).toString('base64');const r=await fetch(base+'/v1/oauth2/token',{method:'POST',headers:{Authorization:'Basic '+auth,'Content-Type':'application/x-www-form-urlencoded'},body:'grant_type=client_credentials'});if(!r.ok)throw new Error('Autenticazione PayPal non riuscita');return {base,token:(await r.json()).access_token}}
async function provisionStripe(plan){if(!stripe||plan.billing_type==='free')return {};const product=plan.stripe_product_id?{id:plan.stripe_product_id}:await stripe.products.create({name:'AirJotter '+plan.name,description:plan.description||undefined,metadata:{airjotter_plan_id:plan.id}});const priceParams={product:product.id,currency:plan.currency.toLowerCase(),unit_amount:Number(plan.amount_cents),metadata:{airjotter_plan_id:plan.id}};if(plan.billing_type==='subscription'||plan.billing_type==='per_seat')priceParams.recurring={interval:plan.interval_unit||'month',interval_count:Number(plan.interval_count||1)};const price=await stripe.prices.create(priceParams);return {stripe_product_id:product.id,stripe_price_id:price.id}}
async function provisionPayPal(plan){if(plan.billing_type==='free'||plan.billing_type==='consumable')return {};const auth=await paypalToken();if(!auth)return {};let productId=plan.paypal_product_id;if(!productId){const r=await fetch(auth.base+'/v1/catalogs/products',{method:'POST',headers:{Authorization:'Bearer '+auth.token,'Content-Type':'application/json','PayPal-Request-Id':crypto.randomUUID()},body:JSON.stringify({name:'AirJotter '+plan.name,description:plan.description||plan.name,type:'SERVICE',category:'SOFTWARE'})});if(!r.ok)throw new Error('Creazione prodotto PayPal non riuscita');productId=(await r.json()).id}const r=await fetch(auth.base+'/v1/billing/plans',{method:'POST',headers:{Authorization:'Bearer '+auth.token,'Content-Type':'application/json','PayPal-Request-Id':crypto.randomUUID()},body:JSON.stringify({product_id:productId,name:plan.name,description:plan.description,status:'ACTIVE',billing_cycles:[{frequency:{interval_unit:(plan.interval_unit||'month').toUpperCase(),interval_count:Number(plan.interval_count||1)},tenure_type:'REGULAR',sequence:1,total_cycles:0,pricing_scheme:{fixed_price:{value:(Number(plan.amount_cents)/100).toFixed(2),currency_code:plan.currency}}}],payment_preferences:{auto_bill_outstanding:true,payment_failure_threshold:1}})});if(!r.ok)throw new Error('Creazione piano PayPal non riuscita');return {paypal_product_id:productId,paypal_plan_id:(await r.json()).id}}
async function grantPurchase(client,userId,plan,provider,externalId,status='paid'){
 if(plan.billing_type==='consumable'){const column={jotter:'spot_jotters',page:'spot_pages',export:'spot_exports'}[plan.consumable_kind];if(column)await client.query(`UPDATE users SET ${column}=${column}+$1 WHERE id=$2`,[Number(plan.consumable_units||1),userId]);}
 else await client.query("UPDATE users SET plan_id=$1,plan_code=$2,subscription_status=$3,subscription_provider=$4,subscription_external_id=$5 WHERE id=$6",[plan.id,plan.code,status,provider,externalId,userId]);
}
async function stripeWebhookHandler(req,res){if(!stripe||!process.env.STRIPE_WEBHOOK_SECRET)return res.status(503).send('Stripe non configurato');let event;try{event=stripe.webhooks.constructEvent(req.body,req.headers['stripe-signature'],process.env.STRIPE_WEBHOOK_SECRET)}catch(e){return res.status(400).send('Firma webhook non valida')}const c=await pool.connect();try{await c.query('BEGIN');const ins=await c.query('INSERT INTO billing_webhook_events(provider,external_event_id,payload) VALUES($1,$2,$3) ON CONFLICT DO NOTHING RETURNING external_event_id',['stripe',event.id,event]);if(!ins.rowCount){await c.query('ROLLBACK');return res.json({received:true,duplicate:true})}if(event.type==='checkout.session.completed'){const s=event.data.object;if(s.metadata?.kind==='credit_topup'){const cents=Number(s.metadata.amountCents||0);const ins=await c.query("INSERT INTO pay_use_transactions(id,user_id,transaction_type,amount_cents,item_type,provider,external_id,description) VALUES($1,$2,'topup',$3,'credit','stripe',$4,'Ricarica credito') ON CONFLICT(provider,external_id) DO NOTHING RETURNING id",[crypto.randomUUID(),s.client_reference_id,cents,s.id]);if(ins.rowCount)await c.query('UPDATE users SET spot_credit_cents=spot_credit_cents+$1 WHERE id=$2',[cents,s.client_reference_id]);}else{const plan=await planById(s.metadata?.planId);if(plan)await grantPurchase(c,s.client_reference_id,plan,'stripe',s.subscription||s.payment_intent||s.id,'active')}await c.query("UPDATE billing_orders SET status='paid',updated_at=now(),raw=$1 WHERE external_id=$2",[s,s.id])}else if(event.type==='customer.subscription.deleted'||event.type==='customer.subscription.paused'){const sub=event.data.object;await c.query("UPDATE users SET subscription_status='suspended' WHERE subscription_external_id=$1",[sub.id])}else if(event.type==='invoice.payment_failed'){const inv=event.data.object;await c.query("UPDATE users SET subscription_status='past_due' WHERE billing_customer_id=$1",[inv.customer])}await c.query('COMMIT');res.json({received:true})}catch(e){await c.query('ROLLBACK');console.error('Webhook Stripe:',e);res.sendStatus(500)}finally{c.release()}}

app.get('/api/plans',async(req,res)=>{const q=await pool.query("SELECT * FROM billing_plans WHERE status='active' AND public=true ORDER BY sort_order,name");res.json(q.rows.map(planPublic))});
app.get('/api/billing/config',(req,res)=>res.json({stripe:Boolean(process.env.STRIPE_PUBLISHABLE_KEY&&process.env.STRIPE_SECRET_KEY),stripePublishableKey:process.env.STRIPE_PUBLISHABLE_KEY||'',paypal:Boolean(process.env.PAYPAL_CLIENT_ID&&process.env.PAYPAL_CLIENT_SECRET),paypalClientId:process.env.PAYPAL_CLIENT_ID||'',paypalEnv:process.env.PAYPAL_ENV||'sandbox'}));
app.get('/api/billing/me',auth,async(req,res)=>{const p=await resolvedPlan(req.user.sub);const orders=await pool.query('SELECT id,provider,kind,status,amount_cents,currency,quantity,created_at FROM billing_orders WHERE user_id=$1 ORDER BY created_at DESC LIMIT 50',[req.user.sub]);res.json({plan:p,orders:orders.rows})});
app.post('/api/billing/stripe/checkout',auth,async(req,res)=>{if(!stripe)return res.status(503).json({error:'Stripe non configurato'});const plan=await planById(req.body.planId);if(!plan||plan.status!=='active'||!plan.public)return res.sendStatus(404);if(plan.billing_type==='free')return res.status(400).json({error:'Il piano Free non richiede pagamento'});const quantity=plan.billing_type==='per_seat'?Math.max(Number(plan.min_seats||1),Number(req.body.quantity||1)):Math.max(1,Number(req.body.quantity||1));const session=await stripe.checkout.sessions.create({mode:plan.billing_type==='consumable'?'payment':'subscription',line_items:[{price:plan.stripe_price_id,quantity}],client_reference_id:req.user.sub,customer_email:req.user.email,success_url:appBaseUrl+'/?billing=success',cancel_url:appBaseUrl+'/?billing=cancel',metadata:{planId:plan.id,quantity:String(quantity)},allow_promotion_codes:true});await pool.query('INSERT INTO billing_orders(id,user_id,plan_id,provider,kind,external_id,status,amount_cents,currency,quantity) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)',[crypto.randomUUID(),req.user.sub,plan.id,'stripe',plan.billing_type==='consumable'?'one_time':'subscription',session.id,'pending',plan.amount_cents,plan.currency,quantity]);res.json({url:session.url})});
app.post('/api/billing/paypal/create',auth,async(req,res)=>{const plan=await planById(req.body.planId);if(!plan||plan.status!=='active'||!plan.public)return res.sendStatus(404);const authp=await paypalToken();if(!authp)return res.status(503).json({error:'PayPal non configurato'});const quantity=plan.billing_type==='per_seat'?Math.max(Number(plan.min_seats||1),Number(req.body.quantity||1)):Math.max(1,Number(req.body.quantity||1));if(plan.billing_type==='consumable'){const r=await fetch(authp.base+'/v2/checkout/orders',{method:'POST',headers:{Authorization:'Bearer '+authp.token,'Content-Type':'application/json','PayPal-Request-Id':crypto.randomUUID()},body:JSON.stringify({intent:'CAPTURE',purchase_units:[{custom_id:req.user.sub+'|'+plan.id,amount:{currency_code:plan.currency,value:((plan.amount_cents*quantity)/100).toFixed(2)}}],application_context:{return_url:appBaseUrl+'/?billing=paypal-return',cancel_url:appBaseUrl+'/?billing=cancel'}})});const order=await r.json();if(!r.ok)return res.status(502).json({error:order.message||'PayPal non disponibile'});await pool.query('INSERT INTO billing_orders(id,user_id,plan_id,provider,kind,external_id,status,amount_cents,currency,quantity) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)',[crypto.randomUUID(),req.user.sub,plan.id,'paypal','one_time',order.id,'pending',plan.amount_cents,plan.currency,quantity]);return res.json({id:order.id,url:order.links?.find(x=>x.rel==='approve')?.href})}if(!plan.paypal_plan_id)return res.status(400).json({error:'Piano PayPal non ancora configurato'});const r=await fetch(authp.base+'/v1/billing/subscriptions',{method:'POST',headers:{Authorization:'Bearer '+authp.token,'Content-Type':'application/json','PayPal-Request-Id':crypto.randomUUID()},body:JSON.stringify({plan_id:plan.paypal_plan_id,quantity:String(quantity),custom_id:req.user.sub+'|'+plan.id,application_context:{return_url:appBaseUrl+'/?billing=paypal-return',cancel_url:appBaseUrl+'/?billing=cancel',user_action:'SUBSCRIBE_NOW'}})});const sub=await r.json();if(!r.ok)return res.status(502).json({error:sub.message||'PayPal non disponibile'});await pool.query('INSERT INTO billing_orders(id,user_id,plan_id,provider,kind,external_id,status,amount_cents,currency,quantity) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)',[crypto.randomUUID(),req.user.sub,plan.id,'paypal','subscription',sub.id,'pending',plan.amount_cents,plan.currency,quantity]);res.json({id:sub.id,url:sub.links?.find(x=>x.rel==='approve')?.href})});
app.post('/api/billing/paypal/capture',auth,async(req,res)=>{const authp=await paypalToken();if(!authp)return res.status(503).json({error:'PayPal non configurato'});const order=(await pool.query("SELECT * FROM billing_orders WHERE external_id=$1 AND user_id=$2 AND provider='paypal' FOR UPDATE",[req.body.orderId,req.user.sub])).rows[0];if(!order)return res.sendStatus(404);const plan=await planById(order.plan_id);if(order.kind==='one_time'){const r=await fetch(authp.base+'/v2/checkout/orders/'+order.external_id+'/capture',{method:'POST',headers:{Authorization:'Bearer '+authp.token,'Content-Type':'application/json','PayPal-Request-Id':crypto.randomUUID()}});const data=await r.json();if(!r.ok)return res.status(502).json({error:data.message||'Cattura PayPal non riuscita'});const c=await pool.connect();try{await c.query('BEGIN');await grantPurchase(c,req.user.sub,plan,'paypal',order.external_id,'active');await c.query("UPDATE billing_orders SET status='paid',raw=$1,updated_at=now() WHERE id=$2",[data,order.id]);await c.query('COMMIT')}catch(e){await c.query('ROLLBACK');throw e}finally{c.release()}return res.json({ok:true})}res.json({ok:true,pendingWebhook:true})});


async function payUseSettings(){return (await pool.query('SELECT * FROM pay_use_settings WHERE id=1')).rows[0]}
function payUsePublic(x){return {enabled:Boolean(x.enabled),currency:x.currency,minimumTopupCents:Number(x.minimum_topup_cents),jotterCostCents:Number(x.jotter_cost_cents),pageCostCents:Number(x.page_cost_cents),exportCostCents:Number(x.export_cost_cents)}}
app.get('/api/pay-use',auth,async(req,res)=>{const s=await payUseSettings(),u=(await pool.query('SELECT spot_credit_cents FROM users WHERE id=$1',[req.user.sub])).rows[0],tx=await pool.query('SELECT transaction_type,amount_cents,item_type,units,description,created_at FROM pay_use_transactions WHERE user_id=$1 ORDER BY created_at DESC LIMIT 30',[req.user.sub]);res.json({...payUsePublic(s),balanceCents:Number(u?.spot_credit_cents||0),transactions:tx.rows})});
app.post('/api/pay-use/spend',auth,async(req,res)=>{const kind=String(req.body.kind||''),units=Math.max(1,Math.min(100,Number(req.body.units||1)));if(!['jotter','page','export'].includes(kind))return res.status(400).json({error:'Tipo di credito non valido'});const s=await payUseSettings();if(!s.enabled)return res.status(403).json({error:'Pay per Use non disponibile'});const costs={jotter:Number(s.jotter_cost_cents),page:Number(s.page_cost_cents),export:Number(s.export_cost_cents)},columns={jotter:'spot_jotters',page:'spot_pages',export:'spot_exports'},total=costs[kind]*units,c=await pool.connect();try{await c.query('BEGIN');const u=(await c.query('SELECT spot_credit_cents FROM users WHERE id=$1 FOR UPDATE',[req.user.sub])).rows[0];if(Number(u?.spot_credit_cents||0)<total){await c.query('ROLLBACK');return res.status(402).json({error:'Credito insufficiente. Effettua una ricarica di almeno '+(Number(s.minimum_topup_cents)/100).toFixed(2)+' €.'})}await c.query(`UPDATE users SET spot_credit_cents=spot_credit_cents-$1,${columns[kind]}=${columns[kind]}+$2 WHERE id=$3`,[total,units,req.user.sub]);await c.query("INSERT INTO pay_use_transactions(id,user_id,transaction_type,amount_cents,item_type,units,description) VALUES($1,$2,'spend',$3,$4,$5,$6)",[crypto.randomUUID(),req.user.sub,-total,kind,units,`Acquisto ${units} ${kind}`]);await c.query('COMMIT');res.json({ok:true,balanceCents:Number(u.spot_credit_cents)-total,kind,units})}catch(e){await c.query('ROLLBACK');throw e}finally{c.release()}});
app.post('/api/pay-use/stripe/topup',auth,async(req,res)=>{if(!stripe)return res.status(503).json({error:'Stripe non configurato'});const s=await payUseSettings(),amount=Math.round(Number(req.body.amountCents||0));if(amount<Number(s.minimum_topup_cents))return res.status(400).json({error:'La ricarica minima è '+(Number(s.minimum_topup_cents)/100).toFixed(2)+' €'});const session=await stripe.checkout.sessions.create({mode:'payment',line_items:[{price_data:{currency:s.currency.toLowerCase(),unit_amount:amount,product_data:{name:'Credito AirJotter Pay per Use'}},quantity:1}],client_reference_id:req.user.sub,customer_email:req.user.email,success_url:appBaseUrl+'/?billing=credit-success',cancel_url:appBaseUrl+'/?billing=cancel',metadata:{kind:'credit_topup',amountCents:String(amount)}});await pool.query("INSERT INTO billing_orders(id,user_id,provider,kind,external_id,status,amount_cents,currency,quantity) VALUES($1,$2,'stripe','one_time',$3,'pending',$4,$5,1)",[crypto.randomUUID(),req.user.sub,session.id,amount,s.currency]);res.json({url:session.url})});
app.post('/api/pay-use/paypal/topup',auth,async(req,res)=>{const authp=await paypalToken();if(!authp)return res.status(503).json({error:'PayPal non configurato'});const s=await payUseSettings(),amount=Math.round(Number(req.body.amountCents||0));if(amount<Number(s.minimum_topup_cents))return res.status(400).json({error:'La ricarica minima è '+(Number(s.minimum_topup_cents)/100).toFixed(2)+' €'});const id=crypto.randomUUID();const r=await fetch(authp.base+'/v2/checkout/orders',{method:'POST',headers:{Authorization:'Bearer '+authp.token,'Content-Type':'application/json','PayPal-Request-Id':id},body:JSON.stringify({intent:'CAPTURE',purchase_units:[{custom_id:req.user.sub+'|credit|'+amount,description:'Credito AirJotter Pay per Use',amount:{currency_code:s.currency,value:(amount/100).toFixed(2)}}],application_context:{return_url:appBaseUrl+'/?billing=paypal-credit-return',cancel_url:appBaseUrl+'/?billing=cancel'}})});const order=await r.json();if(!r.ok)return res.status(502).json({error:order.message||'PayPal non disponibile'});await pool.query("INSERT INTO billing_orders(id,user_id,provider,kind,external_id,status,amount_cents,currency,quantity,raw) VALUES($1,$2,'paypal','one_time',$3,'pending',$4,$5,1,$6)",[id,req.user.sub,order.id,amount,s.currency,JSON.stringify({payUseTopup:true})]);res.json({id:order.id,url:order.links?.find(x=>x.rel==='approve')?.href})});
app.post('/api/pay-use/paypal/capture',auth,async(req,res)=>{const authp=await paypalToken();if(!authp)return res.status(503).json({error:'PayPal non configurato'});const c=await pool.connect();try{await c.query('BEGIN');const order=(await c.query("SELECT * FROM billing_orders WHERE external_id=$1 AND user_id=$2 AND provider='paypal' FOR UPDATE",[req.body.orderId,req.user.sub])).rows[0];if(!order)return res.sendStatus(404);if(order.status==='paid'){await c.query('ROLLBACK');return res.json({ok:true,duplicate:true})}const rr=await fetch(authp.base+'/v2/checkout/orders/'+order.external_id+'/capture',{method:'POST',headers:{Authorization:'Bearer '+authp.token,'Content-Type':'application/json','PayPal-Request-Id':crypto.randomUUID()}}),data=await rr.json();if(!rr.ok){await c.query('ROLLBACK');return res.status(502).json({error:data.message||'Cattura PayPal non riuscita'})}const ins=await c.query("INSERT INTO pay_use_transactions(id,user_id,transaction_type,amount_cents,item_type,provider,external_id,description) VALUES($1,$2,'topup',$3,'credit','paypal',$4,'Ricarica credito') ON CONFLICT(provider,external_id) DO NOTHING RETURNING id",[crypto.randomUUID(),req.user.sub,Number(order.amount_cents),order.external_id]);if(ins.rowCount)await c.query('UPDATE users SET spot_credit_cents=spot_credit_cents+$1 WHERE id=$2',[Number(order.amount_cents),req.user.sub]);await c.query("UPDATE billing_orders SET status='paid',raw=$1,updated_at=now() WHERE id=$2",[data,order.id]);await c.query('COMMIT');res.json({ok:true})}catch(e){await c.query('ROLLBACK');throw e}finally{c.release()}});
app.get('/api/admin/pay-use',auth,adminOnly,async(req,res)=>res.json(payUsePublic(await payUseSettings())));
app.patch('/api/admin/pay-use',auth,adminOnly,async(req,res)=>{const b=req.body,q=await pool.query('UPDATE pay_use_settings SET enabled=COALESCE($1,enabled),currency=COALESCE($2,currency),minimum_topup_cents=COALESCE($3,minimum_topup_cents),jotter_cost_cents=COALESCE($4,jotter_cost_cents),page_cost_cents=COALESCE($5,page_cost_cents),export_cost_cents=COALESCE($6,export_cost_cents),updated_at=now() WHERE id=1 RETURNING *',[b.enabled??null,b.currency?.toUpperCase()??null,b.minimumTopupCents??null,b.jotterCostCents??null,b.pageCostCents??null,b.exportCostCents??null]);res.json(payUsePublic(q.rows[0]))});
app.get('/api/admin/plans',auth,adminOnly,async(req,res)=>{const q=await pool.query('SELECT * FROM billing_plans ORDER BY sort_order,name');res.json(q.rows.map(r=>({...planPublic(r),stripeProductId:r.stripe_product_id,stripePriceId:r.stripe_price_id,paypalProductId:r.paypal_product_id,paypalPlanId:r.paypal_plan_id})))});
app.post('/api/admin/plans',auth,adminOnly,async(req,res)=>{const b=req.body,id=crypto.randomUUID(),code=String(b.code||b.name||'plan').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,50);const q=await pool.query(`INSERT INTO billing_plans(id,code,name,description,status,billing_type,currency,amount_cents,interval_unit,interval_count,min_seats,max_seats,boards_limit,pages_limit,guests_limit,exports_limit,history_days,included_spot_jotters,included_spot_pages,included_spot_exports,features,consumable_kind,consumable_units,sort_order,featured,public) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,$22,$23,$24,$25,$26) RETURNING *`,[id,code,b.name,b.description||'',b.status||'draft',b.billingType||'subscription',(b.currency||'EUR').toUpperCase(),Number(b.amountCents||0),b.intervalUnit||null,Number(b.intervalCount||1),Number(b.minSeats||1),b.maxSeats||null,Number(b.limits?.boards||1),Number(b.limits?.pages||3),b.limits?.guests??null,b.limits?.exports??null,b.limits?.historyDays??null,Number(b.included?.jotters||0),Number(b.included?.pages||0),Number(b.included?.exports||0),JSON.stringify(b.features||[]),b.consumableKind||null,Number(b.consumableUnits||0),Number(b.sortOrder||0),Boolean(b.featured),b.public!==false]);let row=q.rows[0];try{const remote={...(await provisionStripe(row)),...(await provisionPayPal(row))};if(Object.keys(remote).length){row=(await pool.query('UPDATE billing_plans SET stripe_product_id=COALESCE($1,stripe_product_id),stripe_price_id=COALESCE($2,stripe_price_id),paypal_product_id=COALESCE($3,paypal_product_id),paypal_plan_id=COALESCE($4,paypal_plan_id) WHERE id=$5 RETURNING *',[remote.stripe_product_id||null,remote.stripe_price_id||null,remote.paypal_product_id||null,remote.paypal_plan_id||null,id])).rows[0]}}catch(e){console.warn('Provisioning provider:',e.message)}res.status(201).json(planPublic(row))});
app.patch('/api/admin/plans/:id',auth,adminOnly,async(req,res)=>{const old=await planById(req.params.id);if(!old)return res.sendStatus(404);const b=req.body,priceChanged=b.amountCents!=null&&Number(b.amountCents)!==Number(old.amount_cents);const q=await pool.query(`UPDATE billing_plans SET name=COALESCE($1,name),description=COALESCE($2,description),status=COALESCE($3,status),billing_type=COALESCE($4,billing_type),currency=COALESCE($5,currency),amount_cents=COALESCE($6,amount_cents),interval_unit=COALESCE($7,interval_unit),interval_count=COALESCE($8,interval_count),min_seats=COALESCE($9,min_seats),max_seats=$10,boards_limit=COALESCE($11,boards_limit),pages_limit=COALESCE($12,pages_limit),guests_limit=$13,exports_limit=$14,history_days=$15,included_spot_jotters=COALESCE($16,included_spot_jotters),included_spot_pages=COALESCE($17,included_spot_pages),included_spot_exports=COALESCE($18,included_spot_exports),features=COALESCE($19,features),consumable_kind=$20,consumable_units=COALESCE($21,consumable_units),sort_order=COALESCE($22,sort_order),featured=COALESCE($23,featured),public=COALESCE($24,public),updated_at=now() WHERE id=$25 RETURNING *`,[b.name??null,b.description??null,b.status??null,b.billingType??null,b.currency?.toUpperCase()??null,b.amountCents??null,b.intervalUnit??null,b.intervalCount??null,b.minSeats??null,b.maxSeats??old.max_seats,b.limits?.boards??null,b.limits?.pages??null,b.limits?.guests??old.guests_limit,b.limits?.exports??old.exports_limit,b.limits?.historyDays??old.history_days,b.included?.jotters??null,b.included?.pages??null,b.included?.exports??null,b.features?JSON.stringify(b.features):null,b.consumableKind??old.consumable_kind,b.consumableUnits??null,b.sortOrder??null,b.featured??null,b.public??null,req.params.id]);let row=q.rows[0];if(priceChanged){try{const remote={...(await provisionStripe({...row,stripe_price_id:null})),...(await provisionPayPal({...row,paypal_plan_id:null}))};row=(await pool.query('UPDATE billing_plans SET stripe_product_id=COALESCE($1,stripe_product_id),stripe_price_id=COALESCE($2,stripe_price_id),paypal_product_id=COALESCE($3,paypal_product_id),paypal_plan_id=COALESCE($4,paypal_plan_id) WHERE id=$5 RETURNING *',[remote.stripe_product_id||null,remote.stripe_price_id||null,remote.paypal_product_id||null,remote.paypal_plan_id||null,row.id])).rows[0]}catch(e){console.warn('Nuovo prezzo provider:',e.message)}}res.json(planPublic(row))});
app.delete('/api/admin/plans/:id',auth,adminOnly,async(req,res)=>{const used=Number((await pool.query('SELECT count(*) FROM users WHERE plan_id=$1',[req.params.id])).rows[0].count);if(used)return res.status(409).json({error:'Piano assegnato a utenti: archiviarlo invece di eliminarlo'});const q=await pool.query('DELETE FROM billing_plans WHERE id=$1 RETURNING id',[req.params.id]);if(!q.rowCount)return res.sendStatus(404);res.json({deleted:true})});
app.get('/api/admin/billing/orders',auth,adminOnly,async(req,res)=>{const q=await pool.query('SELECT o.*,u.email,p.name plan_name FROM billing_orders o JOIN users u ON u.id=o.user_id LEFT JOIN billing_plans p ON p.id=o.plan_id ORDER BY o.created_at DESC LIMIT 500');res.json(q.rows)});

app.get('/privacy',(req,res)=>res.sendFile(path.join(process.cwd(),'public','privacy.html')));
app.get('/terms',(req,res)=>res.sendFile(path.join(process.cwd(),'public','terms.html')));
app.post('/api/boards/cleanup-empty',auth,async(req,res)=>{const deleted=await startupCleanup(req.user.sub);res.json({deleted})});
app.get('/api/health',(req,res)=>res.json({ok:true}));
app.get('/api/config',(req,res)=>res.json({googleClientId:process.env.GOOGLE_CLIENT_ID||'',devAuth:process.env.DEV_AUTH==='true'}));
app.post('/api/auth/google',async(req,res)=>{try{const t=await google.verifyIdToken({idToken:req.body.credential,audience:process.env.GOOGLE_CLIENT_ID}); const p=t.getPayload(); if(!p?.sub||!p?.email||p.email_verified!==true)return res.status(401).json({error:'Account Google senza email verificata'}); const id=crypto.randomUUID(); const q=await pool.query(`INSERT INTO users(id,google_sub,email,display_name,avatar_url) VALUES($1,$2,$3,$4,$5) ON CONFLICT(google_sub) DO UPDATE SET email=EXCLUDED.email,display_name=EXCLUDED.display_name,avatar_url=EXCLUDED.avatar_url RETURNING *`,[id,p.sub,p.email,p.name||p.email,p.picture||null]); await pool.query('UPDATE users SET last_login_at=now() WHERE id=$1',[q.rows[0].id]);await pool.query('INSERT INTO login_events(id,user_id) VALUES($1,$2)',[crypto.randomUUID(),q.rows[0].id]);res.cookie('aj_session',tokenFor(q.rows[0],{authProvider:'google',googleSub:p.sub,emailVerified:p.email_verified===true}),{httpOnly:true,secure:process.env.NODE_ENV==='production',sameSite:'lax',maxAge:604800000});res.json({ok:true,user:q.rows[0]})}catch(error){console.error('Verifica Google:',error.message);res.status(401).json({error:'Credenziale Google non valida'})}});
app.post('/api/auth/dev',async(req,res)=>{try{if(process.env.DEV_AUTH!=='true')return res.status(404).json({error:'Accesso test disattivato'});const email=String(req.body.email||'demo@airjotter.local').trim().toLowerCase();const name=String(req.body.name||email.split('@')[0]).trim();if(!email||!name)return res.status(400).json({error:'Nome ed email sono obbligatori'});const id=crypto.randomUUID();const query=await pool.query(`INSERT INTO users(id,email,display_name) VALUES($1,$2,$3) ON CONFLICT(email) DO UPDATE SET display_name=EXCLUDED.display_name RETURNING *`,[id,email,name]);const user=query.rows[0];if(user.is_suspended)return res.status(403).json({error:'Account sospeso. Contatta il titolare di AirJotter.'});if(user.is_suspended)return res.status(403).json({error:'Account sospeso. Contatta il titolare di AirJotter.'});try{await pool.query('UPDATE users SET last_login_at=now() WHERE id=$1',[user.id]);await pool.query('INSERT INTO login_events(id,user_id) VALUES($1,$2)',[crypto.randomUUID(),user.id])}catch(metricError){console.warn('Metriche accesso non registrate:',metricError.message)}res.cookie('aj_session',tokenFor(user),{httpOnly:true,secure:process.env.NODE_ENV==='production',sameSite:'lax',maxAge:604800000});res.json({ok:true,user})}catch(error){console.error('Errore accesso sviluppo:',error);res.status(500).json({error:'Accesso non riuscito: '+error.message})}});
app.get('/api/me',auth,async(req,res)=>{const isAdmin=String(req.user.email||'').toLowerCase()===ADMIN_EMAIL;if(isAdmin)await pool.query("UPDATE users SET plan_code='unlimited' WHERE id=$1",[req.user.sub]);const rp=isAdmin?{code:'unlimited',name:'Unlimited',boards:Number.MAX_SAFE_INTEGER,pages:50,spotJotters:0,spotPages:0,spotExports:0}:await resolvedPlan(req.user.sub);res.json({...req.user,plan:rp.code,planName:rp.name,limits:{boards:rp.boards+rp.spotJotters,pages:rp.pages+rp.spotPages},credits:{jotters:rp.spotJotters,pages:rp.spotPages,exports:rp.spotExports,balanceCents:rp.spotCreditCents||0},isAdmin})});
app.post('/api/boards',auth,async(req,res)=>{const rp=await resolvedPlan(req.user.sub),plan=rp.code,isOwner=String(req.user.email||'').toLowerCase()===ADMIN_EMAIL,limit=isOwner?Number.MAX_SAFE_INTEGER:rp.boards+rp.spotJotters;for(let i=0;i<12;i++){const id=crypto.randomUUID(),code=randomCode(),c=await pool.connect();try{await c.query('BEGIN');await c.query('SELECT pg_advisory_xact_lock(hashtext($1))',[req.user.sub]);await c.query('DELETE FROM boards WHERE owner_user_id=$1 AND is_empty=true AND is_current=false',[req.user.sub]);const count=Number((await c.query('SELECT count(*) FROM boards WHERE owner_user_id=$1',[req.user.sub])).rows[0].count);if(count>=limit){await c.query('ROLLBACK');return res.status(403).json({error:`Il piano ${plan.toUpperCase()} consente massimo ${limit} Jotter di proprietà.`})}await c.query('UPDATE boards SET is_current=false WHERE owner_user_id=$1',[req.user.sub]);await c.query('INSERT INTO boards(id,room_code,owner_user_id,title,is_empty,is_current) VALUES($1,$2,$3,$4,true,true)',[id,code,req.user.sub,req.body.title||'Jotter senza titolo']);await c.query("INSERT INTO board_members(board_id,user_id,role,status) VALUES($1,$2,'owner','approved')",[id,req.user.sub]);await c.query('COMMIT');return res.status(201).json({id,roomCode:code,title:req.body.title||'Jotter senza titolo',url:`${process.env.APP_URL}/?room=${code}`,role:'owner',ownerName:req.user.name,isCurrent:true})}catch(e){await c.query('ROLLBACK');if(e.code!=='23505')throw e}finally{c.release()}}res.status(503).json({error:'Impossibile generare un codice univoco'})});
app.post('/api/boards/join',auth,async(req,res)=>{const raw=String(req.body.roomCode||'').trim().toUpperCase().replace(/[^A-Z0-9]/g,'');const c=raw.length===8?raw.slice(0,4)+'-'+raw.slice(4):String(req.body.roomCode||'').trim().toUpperCase();const q=await pool.query('SELECT b.*,u.display_name AS owner_name FROM boards b JOIN users u ON u.id=b.owner_user_id WHERE b.room_code=$1',[c]);if(!q.rows[0])return res.status(404).json({error:'Jotter non trovato'});const b=q.rows[0];if(b.owner_user_id===req.user.sub){await pool.query('BEGIN');try{await pool.query('UPDATE boards SET is_current=false WHERE owner_user_id=$1',[req.user.sub]);await pool.query('UPDATE boards SET is_current=true,empty_cleanup_after=NULL WHERE id=$1',[b.id]);await pool.query('COMMIT')}catch(e){await pool.query('ROLLBACK');throw e}}else await pool.query('UPDATE boards SET empty_cleanup_after=NULL WHERE id=$1',[b.id]);await pool.query("INSERT INTO board_members(board_id,user_id,role,status) VALUES($1,$2,'viewer','approved') ON CONFLICT DO NOTHING",[b.id,req.user.sub]);const r=await role(b.id,req.user.sub);if(!r||r.status==='revoked')return res.status(403).json({error:'Accesso a questo Jotter sospeso dal proprietario'});res.json({id:b.id,roomCode:b.room_code,title:b.title,revision:b.revision,role:r.role,ownerName:b.owner_name})});
app.get('/api/my/boards',auth,async(req,res)=>{try{await startupCleanup(req.user.sub);const q=await pool.query("SELECT b.id,b.room_code,b.title,b.created_at,b.content_updated_at,b.is_current,u.display_name AS owner_name,m.role FROM board_members m JOIN boards b ON b.id=m.board_id JOIN users u ON u.id=b.owner_user_id WHERE m.user_id=$1 AND m.status='approved' ORDER BY (b.owner_user_id=$1 AND b.is_current=true) DESC,b.content_updated_at DESC",[req.user.sub]);res.json(q.rows.map(x=>({id:x.id,roomCode:x.room_code,title:x.title||'Jotter senza titolo',createdAt:x.created_at,contentUpdatedAt:x.content_updated_at,ownerName:x.owner_name,role:x.role,isCurrent:x.role==='owner'&&x.is_current===true})));}catch(error){console.error('Elenco Jotter:',error);res.status(500).json({error:'Impossibile caricare i Jotter'})}});
app.post('/api/boards/:id/leave',auth,async(req,res)=>{const b=await pool.query('SELECT owner_user_id FROM boards WHERE id=$1',[req.params.id]);if(!b.rows[0])return res.sendStatus(404);if(b.rows[0].owner_user_id===req.user.sub)return res.status(400).json({error:'Il proprietario non puo uscire dal proprio Jotter (puo solo eliminarlo).'});const q=await pool.query('DELETE FROM board_members WHERE board_id=$1 AND user_id=$2 RETURNING board_id',[req.params.id,req.user.sub]);if(!q.rows[0])return res.sendStatus(404);res.json({left:true,id:req.params.id})});
app.patch('/api/boards/:id/title',auth,async(req,res)=>{const title=String(req.body.title||'').trim().slice(0,120);if(!title)return res.status(400).json({error:'Titolo non valido'});const q=await pool.query('UPDATE boards SET title=$1 WHERE id=$2 AND owner_user_id=$3 RETURNING id,title,content_updated_at',[title,req.params.id,req.user.sub]);if(!q.rows[0])return res.sendStatus(403);res.json({id:q.rows[0].id,title:q.rows[0].title,contentUpdatedAt:q.rows[0].content_updated_at})});
app.delete('/api/boards/:id',auth,async(req,res)=>{const q=await pool.query('DELETE FROM boards WHERE id=$1 AND owner_user_id=$2 RETURNING id',[req.params.id,req.user.sub]);if(!q.rows[0])return res.sendStatus(403);res.json({deleted:true,id:q.rows[0].id})});
app.get('/api/admin/stats',auth,adminOnly,async(req,res)=>{const [u,b,l,o,p]=await Promise.all([pool.query("SELECT count(*)::int total,count(*) FILTER(WHERE created_at>=current_date)::int today,count(*) FILTER(WHERE created_at>=now()-interval '7 days')::int week FROM users"),pool.query("SELECT count(*)::int total,count(*) FILTER(WHERE created_at>=current_date)::int today,count(*) FILTER(WHERE content_updated_at>=now()-interval '24 hours')::int active FROM boards"),pool.query("SELECT count(*)::int total,count(*) FILTER(WHERE created_at>=current_date)::int today,count(DISTINCT user_id) FILTER(WHERE created_at>=now()-interval '24 hours')::int active_users FROM login_events"),pool.query('SELECT count(*)::int total FROM board_operations'),pool.query('SELECT plan_code,count(*)::int count FROM users GROUP BY plan_code')]);res.json({users:u.rows[0],boards:b.rows[0],logins:l.rows[0],operations:o.rows[0].total,plans:p.rows,online:io.engine.clientsCount,updatedAt:new Date().toISOString()})});
app.get('/api/admin/users',auth,adminOnly,async(req,res)=>{const x=await pool.query('SELECT u.id,u.email,u.display_name,u.plan_code,u.created_at,u.last_login_at,u.is_suspended,count(b.id)::int AS boards FROM users u LEFT JOIN boards b ON b.owner_user_id=u.id GROUP BY u.id ORDER BY u.created_at DESC LIMIT 500');res.json(x.rows.map(r=>({id:r.id,email:r.email,name:r.display_name,plan:r.plan_code,createdAt:r.created_at,lastLoginAt:r.last_login_at,suspended:r.is_suspended,boards:r.boards}))) });
app.patch('/api/admin/users/:id/suspension',auth,adminOnly,async(req,res)=>{const target=await pool.query('SELECT id,email,is_suspended FROM users WHERE id=$1',[req.params.id]);const u=target.rows[0];if(!u)return res.sendStatus(404);if(String(u.email).toLowerCase()===ADMIN_EMAIL)return res.status(400).json({error:'Il titolare non può essere sospeso'});const suspended=Boolean(req.body.suspended);const x=await pool.query('UPDATE users SET is_suspended=$1,suspended_at=CASE WHEN $1 THEN now() ELSE NULL END WHERE id=$2 RETURNING id,email,is_suspended',[suspended,u.id]);if(suspended){for(const [id,socket] of io.of('/').sockets){if(socket.user?.sub===u.id){socket.emit('account:suspended');socket.disconnect(true)}}}res.json({id:x.rows[0].id,email:x.rows[0].email,suspended:x.rows[0].is_suspended})});
app.delete('/api/admin/users/:id',auth,adminOnly,async(req,res)=>{const client=await pool.connect();try{await client.query('BEGIN');const target=await client.query('SELECT id,email FROM users WHERE id=$1 FOR UPDATE',[req.params.id]);const u=target.rows[0];if(!u){await client.query('ROLLBACK');return res.sendStatus(404)}if(String(u.email).toLowerCase()===ADMIN_EMAIL){await client.query('ROLLBACK');return res.status(400).json({error:'Il titolare non può essere eliminato'})}for(const [socketId,socket] of io.of('/').sockets){if(socket.user?.sub===u.id){socket.emit('account:deleted');socket.disconnect(true)}}await client.query('UPDATE board_operations SET user_id=NULL WHERE user_id=$1',[u.id]);await client.query('DELETE FROM boards WHERE owner_user_id=$1',[u.id]);await client.query('DELETE FROM board_members WHERE user_id=$1',[u.id]);await client.query('DELETE FROM access_requests WHERE requester_user_id=$1',[u.id]);await client.query('DELETE FROM login_events WHERE user_id=$1',[u.id]);await client.query('DELETE FROM users WHERE id=$1',[u.id]);await client.query('COMMIT');res.json({deleted:true,id:u.id})}catch(error){await client.query('ROLLBACK');console.error('Eliminazione utente:',error);res.status(500).json({error:'Eliminazione non riuscita: '+error.message})}finally{client.release()}});

app.get('/api/boards/:id/access',auth,async(req,res)=>{
 const b=(await pool.query('SELECT id,title,room_code,owner_user_id FROM boards WHERE id=$1',[req.params.id])).rows[0];
 if(!b)return res.sendStatus(404);if(b.owner_user_id!==req.user.sub)return res.sendStatus(403);
 const members=await pool.query("SELECT bm.user_id,bm.role,bm.status,u.display_name,u.email FROM board_members bm JOIN users u ON u.id=bm.user_id WHERE bm.board_id=$1 ORDER BY CASE bm.role WHEN 'owner' THEN 0 WHEN 'editor' THEN 1 ELSE 2 END,u.display_name",[b.id]);
 const requests=await pool.query("SELECT ar.id,ar.requester_user_id,u.display_name,u.email,ar.created_at FROM access_requests ar JOIN users u ON u.id=ar.requester_user_id WHERE ar.board_id=$1 AND ar.status='pending' ORDER BY ar.created_at",[b.id]);
 res.json({id:b.id,title:b.title,roomCode:b.room_code,members:members.rows.map(x=>({userId:x.user_id,name:x.display_name,email:x.email,role:x.role,status:x.status})),requests:requests.rows.map(x=>({requestId:x.id,userId:x.requester_user_id,name:x.display_name,email:x.email,createdAt:x.created_at}))});
});
app.patch('/api/boards/:id/members/:userId/suspension',auth,async(req,res)=>{
 const b=(await pool.query('SELECT owner_user_id FROM boards WHERE id=$1',[req.params.id])).rows[0];if(!b)return res.sendStatus(404);if(b.owner_user_id!==req.user.sub)return res.sendStatus(403);if(req.params.userId===req.user.sub)return res.status(400).json({error:'Il proprietario non può essere sospeso'});
 const suspended=Boolean(req.body.suspended);const q=await pool.query("UPDATE board_members SET status=$1 WHERE board_id=$2 AND user_id=$3 AND role<>'owner' RETURNING user_id,role,status",[suspended?'revoked':'approved',req.params.id,req.params.userId]);if(!q.rows[0])return res.sendStatus(404);
 if(suspended){io.to('user:'+req.params.userId).emit('board:access-suspended',{boardId:req.params.id});}else{io.to('user:'+req.params.userId).emit('board:access-restored',{boardId:req.params.id,role:q.rows[0].role});}res.json({ok:true,suspended,status:q.rows[0].status});
});
app.delete('/api/boards/:id/members/:userId',auth,async(req,res)=>{
 const b=(await pool.query('SELECT owner_user_id FROM boards WHERE id=$1',[req.params.id])).rows[0];if(!b)return res.sendStatus(404);if(b.owner_user_id!==req.user.sub)return res.sendStatus(403);if(req.params.userId===req.user.sub)return res.status(400).json({error:'Il proprietario non può essere eliminato'});
 await pool.query('BEGIN');try{await pool.query('DELETE FROM access_requests WHERE board_id=$1 AND requester_user_id=$2',[req.params.id,req.params.userId]);const q=await pool.query("DELETE FROM board_members WHERE board_id=$1 AND user_id=$2 AND role<>'owner' RETURNING user_id",[req.params.id,req.params.userId]);await pool.query('COMMIT');if(!q.rows[0])return res.sendStatus(404);io.to('user:'+req.params.userId).emit('board:access-removed',{boardId:req.params.id});res.json({deleted:true})}catch(e){await pool.query('ROLLBACK');throw e}
});
app.get('/api/boards/:id/history-state',auth,async(req,res)=>{const r=await role(req.params.id,req.user.sub);if(!r||r.status!=='approved')return res.sendStatus(403);const q=await pool.query('SELECT count(*) FILTER(WHERE is_active=true)::int AS active,count(*) FILTER(WHERE is_active=false)::int AS inactive FROM board_operations WHERE board_id=$1',[req.params.id]);res.json({canUndo:q.rows[0].active>0,canRedo:q.rows[0].inactive>0})});
app.get('/api/boards/:id/operations',auth,async(req,res)=>{const r=await role(req.params.id,req.user.sub);if(!r||r.status!=='approved')return res.sendStatus(403);const q=await pool.query('SELECT revision,operation_id,operation_type,payload,is_active FROM board_operations WHERE board_id=$1 ORDER BY revision',[req.params.id]);res.json(q.rows)});
app.get('/api/boards/:id/qr',auth,async(req,res)=>{const r=await role(req.params.id,req.user.sub);if(!r)return res.sendStatus(403);const q=await pool.query('SELECT room_code FROM boards WHERE id=$1',[req.params.id]);if(!q.rows[0])return res.sendStatus(404);res.type('png');res.send(await QRCode.toBuffer(`${process.env.APP_URL}/?room=${q.rows[0].room_code}`,{width:320,margin:2}))});
app.post('/api/boards/:id/request-edit',auth,async(req,res)=>{const r=await role(req.params.id,req.user.sub);if(!r)return res.sendStatus(403);if(r.role!=='viewer')return res.json({status:r.role});let q=await pool.query("SELECT id FROM access_requests WHERE board_id=$1 AND requester_user_id=$2 AND status='pending'",[req.params.id,req.user.sub]);let id=q.rows[0]?.id;if(!id){id=crypto.randomUUID();await pool.query("INSERT INTO access_requests(id,board_id,requester_user_id) VALUES($1,$2,$3)",[id,req.params.id,req.user.sub]);}const b=await pool.query('SELECT owner_user_id FROM boards WHERE id=$1',[req.params.id]);const event={requestId:id,boardId:req.params.id,name:req.user.name,email:req.user.email};io.to('user:'+b.rows[0].owner_user_id).emit('access:requested',event);res.json({status:'pending',requestId:id})});
app.get('/api/boards/:id/access-requests',auth,async(req,res)=>{const b=await pool.query('SELECT owner_user_id FROM boards WHERE id=$1',[req.params.id]);if(!b.rows[0]||b.rows[0].owner_user_id!==req.user.sub)return res.sendStatus(403);const q=await pool.query("SELECT ar.id,ar.board_id,u.display_name,u.email FROM access_requests ar JOIN users u ON u.id=ar.requester_user_id WHERE ar.board_id=$1 AND ar.status='pending' ORDER BY ar.created_at",[req.params.id]);res.json(q.rows.map(x=>({requestId:x.id,boardId:x.board_id,name:x.display_name,email:x.email})))});
app.post('/api/access/:id/resolve',auth,async(req,res)=>{const q=await pool.query('SELECT ar.*,b.owner_user_id FROM access_requests ar JOIN boards b ON b.id=ar.board_id WHERE ar.id=$1',[req.params.id]);const a=q.rows[0];if(!a||a.owner_user_id!==req.user.sub)return res.sendStatus(403);const approved=!!req.body.approved;await pool.query('BEGIN');await pool.query("UPDATE access_requests SET status=$1,resolved_at=now() WHERE id=$2 AND status='pending'",[approved?'approved':'denied',a.id]);if(approved)await pool.query("UPDATE board_members SET role='editor',status='approved' WHERE board_id=$1 AND user_id=$2",[a.board_id,a.requester_user_id]);await pool.query('COMMIT');io.to(`user:${a.requester_user_id}`).emit('access:resolved',{boardId:a.board_id,approved,role:approved?'editor':'viewer'});res.json({approved})});
io.use(async(socket,next)=>{try{const raw=socket.handshake.headers.cookie||'';const m=raw.match(/(?:^|; )aj_session=([^;]+)/);socket.user=jwt.verify(decodeURIComponent(m?.[1]||''),secret);const u=await pool.query('SELECT is_suspended FROM users WHERE id=$1',[socket.user.sub]);if(!u.rows[0]||u.rows[0].is_suspended)return next(new Error('account_suspended'));next()}catch{next(new Error('unauthorized'))}});
const pub=createClient({url:process.env.REDIS_URL}),sub=pub.duplicate();await Promise.all([pub.connect(),sub.connect()]);io.adapter(createAdapter(pub,sub));
io.on('connection',socket=>{socket.join(`user:${socket.user.sub}`);socket.on('board:join',async({boardId},ack)=>{const r=await role(boardId,socket.user.sub);if(!r||r.status!=='approved')return ack?.({error:'forbidden'});socket.join(`board:${boardId}`);socket.data.currentBoardId=boardId;const own=await pool.query('SELECT owner_user_id FROM boards WHERE id=$1',[boardId]);if(own.rows[0]?.owner_user_id===socket.user.sub)await cancelEmptyCleanup(boardId,socket.user.sub);ack?.({ok:true,role:r.role})});socket.on('disconnect',()=>{});socket.on('stroke:preview',async preview=>{try{if(!preview||preview.boardId!==socket.data.currentBoardId||!preview.strokeId||!Array.isArray(preview.points)||preview.points.length<1||preview.points.length>160)return;const r=await role(preview.boardId,socket.user.sub);if(!r||!['owner','editor'].includes(r.role))return;socket.volatile.to(`board:${preview.boardId}`).emit('stroke:preview',{boardId:preview.boardId,strokeId:String(preview.strokeId).slice(0,80),points:preview.points,color:String(preview.color||'#1D1D1F').slice(0,32),isEraser:Boolean(preview.isEraser),sentAt:Number(preview.sentAt)||Date.now()});}catch{}});socket.on('board:operation',async(op,ack)=>{try{const r=await role(op.boardId,socket.user.sub);if(!r||!['owner','editor'].includes(r.role))return ack?.({error:'readonly'});if(!['stroke:add','text:add','command:add','page:set','page:delete','board:clear'].includes(op.type))return ack?.({error:'invalid'});if(op.type==='page:set'){const maxPages=await boardPageLimit(op.boardId);if(Number(op.payload?.count)>maxPages)return ack?.({error:'page_limit',message:`Il piano del proprietario consente massimo ${maxPages} pagine.`});}const c=await pool.connect();try{await c.query('BEGIN');await c.query('DELETE FROM board_operations WHERE board_id=$1 AND is_active=false',[op.boardId]);const b=await c.query(`UPDATE boards SET revision=revision+1,updated_at=now(),content_updated_at=now(),empty_cleanup_after=NULL,is_empty=CASE WHEN $2='board:clear' THEN true WHEN $2 IN ('command:add','stroke:add','text:add') THEN false ELSE is_empty END WHERE id=$1 RETURNING revision`,[op.boardId,op.type]);const rev=b.rows[0].revision;await c.query('INSERT INTO board_operations(board_id,revision,operation_id,user_id,operation_type,payload) VALUES($1,$2,$3,$4,$5,$6)',[op.boardId,rev,op.operationId,socket.user.sub,op.type,op.payload]);await c.query('COMMIT');const event={...op,revision:rev};socket.to(`board:${op.boardId}`).emit('board:operation',event);ack?.({ok:true,revision:rev})}catch(e){await c.query('ROLLBACK');throw e}finally{c.release()}}catch{ack?.({error:'server'})}});
 socket.on('history:undo',async({boardId},ack)=>{try{const r=await role(boardId,socket.user.sub);if(!r||!['owner','editor'].includes(r.role))return ack?.({error:'readonly'});const q=await pool.query(`UPDATE board_operations SET is_active=false WHERE board_id=$1 AND revision=(SELECT max(revision) FROM board_operations WHERE board_id=$1 AND is_active=true) RETURNING operation_id`,[boardId]);if(q.rowCount){io.to(`board:${boardId}`).emit('board:reload');const st=await pool.query('SELECT count(*) FILTER(WHERE is_active=true)::int active,count(*) FILTER(WHERE is_active=false)::int inactive FROM board_operations WHERE board_id=$1',[boardId]);ack?.({ok:true,canUndo:st.rows[0].active>0,canRedo:st.rows[0].inactive>0})}else ack?.({error:'empty',canUndo:false,canRedo:false})}catch{ack?.({error:'server'})}});
 socket.on('history:redo',async({boardId},ack)=>{try{const r=await role(boardId,socket.user.sub);if(!r||!['owner','editor'].includes(r.role))return ack?.({error:'readonly'});const q=await pool.query(`UPDATE board_operations SET is_active=true WHERE board_id=$1 AND revision=(SELECT min(revision) FROM board_operations WHERE board_id=$1 AND is_active=false) RETURNING operation_id`,[boardId]);if(q.rowCount){io.to(`board:${boardId}`).emit('board:reload');const st=await pool.query('SELECT count(*) FILTER(WHERE is_active=true)::int active,count(*) FILTER(WHERE is_active=false)::int inactive FROM board_operations WHERE board_id=$1',[boardId]);ack?.({ok:true,canUndo:st.rows[0].active>0,canRedo:st.rows[0].inactive>0})}else ack?.({error:'empty',canUndo:true,canRedo:false})}catch{ack?.({error:'server'})}})
});
// v15.6: pulizia deterministica eseguita all'avvio utente e prima della creazione
if(process.env.NODE_ENV==='production'&&process.env.DEV_AUTH==='true')throw new Error('Configurazione non sicura: DEV_AUTH non può essere attivo in produzione');
if(process.env.NODE_ENV==='production'&&!process.env.ADMIN_GOOGLE_SUB)throw new Error('ADMIN_GOOGLE_SUB obbligatorio in produzione');
server.listen(process.env.PORT||3000,()=>console.log(`airjotter su porta ${process.env.PORT||3000}`));
